version: '3.9'

services:
  application:
    build: app
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - database

  database:
    image: postgres:16.2-alpine3.18
    env_file: .env
    restart: unless-stopped
    ports:
      - '5555:5432'
    volumes:
      - database-storage:/var/lib/postgresql/data

volumes:
  database-storage: